name: Gerar Metricas do Perfil

on:
  schedule:
    # Roda todo dia às 03:15 UTC (meia-noite e quinze no horário de Brasília)
    - cron: "15 3 * * *"
  workflow_dispatch: {} # permite rodar manualmente pela aba Actions
  push:
    branches:
      - main

jobs:
  gerar-metricas:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          user: ${{ github.repository_owner }}
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Sao_Paulo
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_limit: 8
          plugin_languages_threshold: 0%
          committer_branch: output
